INSERT INTO `mayor_consumo_view` VALUES ('QUICK', 110277.30, 'QUICK-Stop');
INSERT INTO `mayor_consumo_view` VALUES ('ERNSH', 104874.98, 'Ernst Handel');
INSERT INTO `mayor_consumo_view` VALUES ('SAVEA', 104361.95, 'Save-a-lot Markets');
INSERT INTO `mayor_consumo_view` VALUES ('RATTC', 51097.80, 'Rattlesnake Canyon Grocery');
INSERT INTO `mayor_consumo_view` VALUES ('HUNGO', 49979.90, 'Hungry Owl All-Night Grocers');
INSERT INTO `mayor_consumo_view` VALUES ('HANAR', 32841.37, 'Hanari Carnes');
INSERT INTO `mayor_consumo_view` VALUES ('KOENE', 30908.38, 'Königlich Essen');
INSERT INTO `mayor_consumo_view` VALUES ('FOLKO', 29567.56, 'Folk och fä HB');
INSERT INTO `mayor_consumo_view` VALUES ('MEREP', 28872.19, 'Mère Paillarde');
INSERT INTO `mayor_consumo_view` VALUES ('WHITC', 27363.60, 'White Clover Markets');
INSERT INTO `mayor_consumo_view` VALUES ('FRANK', 26656.56, 'Frankenversand');
INSERT INTO `mayor_consumo_view` VALUES ('QUEEN', 25717.50, 'Queen Cozinha');
INSERT INTO `mayor_consumo_view` VALUES ('BERGS', 24927.58, 'Berglunds snabbköp');
INSERT INTO `mayor_consumo_view` VALUES ('SUPRD', 24088.78, 'Suprêmes délices');
INSERT INTO `mayor_consumo_view` VALUES ('PICCO', 23128.86, 'Piccolo und mehr');
INSERT INTO `mayor_consumo_view` VALUES ('HILAA', 22768.76, 'HILARION-Abastos');
INSERT INTO `mayor_consumo_view` VALUES ('BONAP', 21963.25, 'Bon app\'');
INSERT INTO `mayor_consumo_view` VALUES ('BOTTM', 20801.60, 'Bottom-Dollar Markets');
INSERT INTO `mayor_consumo_view` VALUES ('RICSU', 19343.78, 'Richter Supermarkt');
INSERT INTO `mayor_consumo_view` VALUES ('LEHMS', 19261.41, 'Lehmanns Marktstand');
INSERT INTO `mayor_consumo_view` VALUES ('BLONP', 18534.08, 'Blondesddsl père et fils');
INSERT INTO `mayor_consumo_view` VALUES ('GREAL', 18507.45, 'Great Lakes Food Market');
INSERT INTO `mayor_consumo_view` VALUES ('SIMOB', 16817.10, 'Simons bistro');
INSERT INTO `mayor_consumo_view` VALUES ('LINOD', 16476.56, 'LINO-Delicateses');
INSERT INTO `mayor_consumo_view` VALUES ('SEVES', 16215.32, 'Seven Seas Imports');
INSERT INTO `mayor_consumo_view` VALUES ('LILAS', 16076.60, 'LILA-Supermercado');
INSERT INTO `mayor_consumo_view` VALUES ('VAFFE', 15843.92, 'Vaffeljernet');
INSERT INTO `mayor_consumo_view` VALUES ('WARTH', 15648.70, 'Wartian Herkku');
INSERT INTO `mayor_consumo_view` VALUES ('OLDWO', 15177.46, 'Old World Delicatessen');
INSERT INTO `mayor_consumo_view` VALUES ('EASTC', 14761.04, 'Eastern Connection');
INSERT INTO `mayor_consumo_view` VALUES ('AROUT', 13390.65, 'Around the Horn');
INSERT INTO `mayor_consumo_view` VALUES ('OTTIK', 12496.20, 'Ottilies Käseladen');
INSERT INTO `mayor_consumo_view` VALUES ('RICAR', 12450.80, 'Ricardo Adocicados');
INSERT INTO `mayor_consumo_view` VALUES ('CHOPS', 12348.88, 'Chop-suey Chinese');
INSERT INTO `mayor_consumo_view` VALUES ('FOLIG', 11666.90, 'Folies gourmandes');
INSERT INTO `mayor_consumo_view` VALUES ('GODOS', 11446.36, 'Godos Cocina Típica');
INSERT INTO `mayor_consumo_view` VALUES ('SPLIR', 11441.63, 'Split Rail Beer & Ale');
INSERT INTO `mayor_consumo_view` VALUES ('TORTU', 10812.15, 'Tortuga Restaurante');
INSERT INTO `mayor_consumo_view` VALUES ('MAISD', 9736.07, 'Maison Dewey');
INSERT INTO `mayor_consumo_view` VALUES ('WANDK', 9588.42, 'Die Wandernde Kuh');
INSERT INTO `mayor_consumo_view` VALUES ('LAMAI', 9328.20, 'La maison d\'Asie');
INSERT INTO `mayor_consumo_view` VALUES ('VICTE', 9182.43, 'Victuailles en stock');
INSERT INTO `mayor_consumo_view` VALUES ('GOURL', 8414.13, 'Gourmet Lanchonetes');
INSERT INTO `mayor_consumo_view` VALUES ('MAGAA', 7176.21, 'Magazzini Alimentari Riuniti');
INSERT INTO `mayor_consumo_view` VALUES ('REGGC', 7048.24, 'Reggiani Caseifici');
INSERT INTO `mayor_consumo_view` VALUES ('ANTON', 7023.98, 'Antonio Moreno Taquería');
INSERT INTO `mayor_consumo_view` VALUES ('TRADH', 6850.66, 'Tradição Hipermercados');
INSERT INTO `mayor_consumo_view` VALUES ('QUEDE', 6664.81, 'Que Delícia');
INSERT INTO `mayor_consumo_view` VALUES ('FURIB', 6427.42, 'Furia Bacalhau e Frutos do Mar');
INSERT INTO `mayor_consumo_view` VALUES ('ISLAT', 6146.30, 'Island Trading');
INSERT INTO `mayor_consumo_view` VALUES ('BSBEV', 6089.90, 'B\'s Beverages');
INSERT INTO `mayor_consumo_view` VALUES ('WELLI', 6068.20, 'Wellington Importadora');
INSERT INTO `mayor_consumo_view` VALUES ('SANTG', 5735.15, 'Santé Gourmet');
INSERT INTO `mayor_consumo_view` VALUES ('PRINI', 5044.94, 'Princesa Isabel Vinhos');
INSERT INTO `mayor_consumo_view` VALUES ('MORGK', 5042.20, 'Morgenstern Gesundkost');
INSERT INTO `mayor_consumo_view` VALUES ('TOMSP', 4778.14, 'Toms Spezialitäten');
INSERT INTO `mayor_consumo_view` VALUES ('ALFKI', 4273.00, 'Alfreds Futterkiste');
INSERT INTO `mayor_consumo_view` VALUES ('LONEP', 4258.60, 'Lonesome Pine Restaurant');
INSERT INTO `mayor_consumo_view` VALUES ('PERIC', 4242.20, 'Pericles Comidas clásicas');
INSERT INTO `mayor_consumo_view` VALUES ('BOLID', 4232.85, 'Bólido Comidas preparadas');
INSERT INTO `mayor_consumo_view` VALUES ('FAMIA', 4107.55, 'Familia Arquibaldo');
INSERT INTO `mayor_consumo_view` VALUES ('COMMI', 3810.75, 'Comércio Mineiro');
INSERT INTO `mayor_consumo_view` VALUES ('DRACD', 3763.21, 'Drachenblut Delikatessen');
INSERT INTO `mayor_consumo_view` VALUES ('WOLZA', 3531.95, 'Wolski  Zajazd');
INSERT INTO `mayor_consumo_view` VALUES ('OCEAN', 3460.20, 'Océano Atlántico Ltda.');
INSERT INTO `mayor_consumo_view` VALUES ('THEBI', 3361.00, 'The Big Cheese');
INSERT INTO `mayor_consumo_view` VALUES ('BLAUS', 3239.80, 'Blauer See Delikatessen');
INSERT INTO `mayor_consumo_view` VALUES ('FRANR', 3172.16, 'France restauration');
INSERT INTO `mayor_consumo_view` VALUES ('WILMK', 3161.35, 'Wilman Kala');
INSERT INTO `mayor_consumo_view` VALUES ('LETSS', 3076.47, 'Let\'s Stop N Shop');
INSERT INTO `mayor_consumo_view` VALUES ('HUNGC', 3063.20, 'Hungry Coyote Import Store');
INSERT INTO `mayor_consumo_view` VALUES ('RANCH', 2844.10, 'Rancho grande');
INSERT INTO `mayor_consumo_view` VALUES ('SPECD', 2423.35, 'Spécialités du monde');
INSERT INTO `mayor_consumo_view` VALUES ('LACOR', 1992.05, 'La corne d\'abondance');
INSERT INTO `mayor_consumo_view` VALUES ('THECR', 1947.24, 'The Cracker Box');
INSERT INTO `mayor_consumo_view` VALUES ('CACTU', 1814.80, 'Cactus Comidas para llevar');
INSERT INTO `mayor_consumo_view` VALUES ('CONSH', 1719.10, 'Consolidated Holdings');
INSERT INTO `mayor_consumo_view` VALUES ('DUMON', 1615.90, 'Du monde entier');
INSERT INTO `mayor_consumo_view` VALUES ('TRAIH', 1571.20, 'Trail\'s Head Gourmet Provisioners');
INSERT INTO `mayor_consumo_view` VALUES ('FRANS', 1545.70, 'Franchi S.p.A.');
INSERT INTO `mayor_consumo_view` VALUES ('GROSR', 1488.70, 'GROSELLA-Restaurante');
INSERT INTO `mayor_consumo_view` VALUES ('VINET', 1480.00, 'Vins et alcools Chevalier');
INSERT INTO `mayor_consumo_view` VALUES ('ROMEY', 1467.29, 'Romero y tomillo');
INSERT INTO `mayor_consumo_view` VALUES ('ANATR', 1402.95, 'Ana Trujillo Emparedados y helados');
INSERT INTO `mayor_consumo_view` VALUES ('GALED', 836.70, 'Galería del gastrónomo');
INSERT INTO `mayor_consumo_view` VALUES ('NORTS', 649.00, 'North/South');
INSERT INTO `mayor_consumo_view` VALUES ('LAUGB', 522.50, 'Laughing Bacchus Wine Cellars');
INSERT INTO `mayor_consumo_view` VALUES ('LAZYK', 357.00, 'Lazy K Kountry Store');
INSERT INTO `mayor_consumo_view` VALUES ('CENTC', 100.80, 'Centro comercial Moctezuma');
